//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 15/7/2025 1:20:22 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Sistema.Proctor.Data.Entities
{
    public partial class Limitesatterberg : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private int _IdLimites;

        private int _IdMuestra;

        private decimal _LL;

        private decimal _LP;

        private decimal? _IP;

        private Muestra _Muestra;

        public Limitesatterberg()
        {
            OnCreated();
        }

        public int IdLimites
        {
            get
            {
                return this._IdLimites;
            }
            set
            {
                if (this._IdLimites != value)
                {
                    this.SendPropertyChanging("IdLimites");
                    this._IdLimites = value;
                    this.SendPropertyChanged("IdLimites");
                }
            }
        }

        public int IdMuestra
        {
            get
            {
                return this._IdMuestra;
            }
            set
            {
                if (this._IdMuestra != value)
                {
                    this.SendPropertyChanging("IdMuestra");
                    this._IdMuestra = value;
                    this.SendPropertyChanged("IdMuestra");
                }
            }
        }

        public decimal LL
        {
            get
            {
                return this._LL;
            }
            set
            {
                if (this._LL != value)
                {
                    this.SendPropertyChanging("LL");
                    this._LL = value;
                    this.SendPropertyChanged("LL");
                }
            }
        }

        public decimal LP
        {
            get
            {
                return this._LP;
            }
            set
            {
                if (this._LP != value)
                {
                    this.SendPropertyChanging("LP");
                    this._LP = value;
                    this.SendPropertyChanged("LP");
                }
            }
        }

        public decimal? IP
        {
            get
            {
                return this._IP;
            }
            set
            {
                if (this._IP != value)
                {
                    this.SendPropertyChanging("IP");
                    this._IP = value;
                    this.SendPropertyChanged("IP");
                }
            }
        }

        public virtual Muestra Muestra
        {
            get
            {
                return this._Muestra;
            }
            set
            {
                if (this._Muestra != value)
                {
                    this.SendPropertyChanging("Muestra");
                    this._Muestra = value;
                    this.SendPropertyChanged("Muestra");
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          Limitesatterberg toCompare = obj as Limitesatterberg;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.IdLimites, toCompare.IdLimites))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + IdLimites.GetHashCode();
          return hashCode;
        }

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
