//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 15/7/2025 1:20:22 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Sistema.Proctor.Data.Entities
{
    public partial class Granulometriadetalle : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private int _IdDetalle;

        private int _IdGranulometria;

        private string _Tamiz;

        private decimal? _TamanoMM;

        private decimal? _Retenido1;

        private decimal? _Retenido2;

        private decimal? _RetenidoPorcentaje;

        private decimal? _RetenidoAcumulado;

        private decimal? _PorcentajePasa;

        private Granulometria _Granulometria;

        public Granulometriadetalle()
        {
            OnCreated();
        }

        public int IdDetalle
        {
            get
            {
                return this._IdDetalle;
            }
            set
            {
                if (this._IdDetalle != value)
                {
                    this.SendPropertyChanging("IdDetalle");
                    this._IdDetalle = value;
                    this.SendPropertyChanged("IdDetalle");
                }
            }
        }

        public int IdGranulometria
        {
            get
            {
                return this._IdGranulometria;
            }
            set
            {
                if (this._IdGranulometria != value)
                {
                    this.SendPropertyChanging("IdGranulometria");
                    this._IdGranulometria = value;
                    this.SendPropertyChanged("IdGranulometria");
                }
            }
        }

        public string Tamiz
        {
            get
            {
                return this._Tamiz;
            }
            set
            {
                if (this._Tamiz != value)
                {
                    this.SendPropertyChanging("Tamiz");
                    this._Tamiz = value;
                    this.SendPropertyChanged("Tamiz");
                }
            }
        }

        public decimal? TamanoMM
        {
            get
            {
                return this._TamanoMM;
            }
            set
            {
                if (this._TamanoMM != value)
                {
                    this.SendPropertyChanging("TamanoMM");
                    this._TamanoMM = value;
                    this.SendPropertyChanged("TamanoMM");
                }
            }
        }

        public decimal? Retenido1
        {
            get
            {
                return this._Retenido1;
            }
            set
            {
                if (this._Retenido1 != value)
                {
                    this.SendPropertyChanging("Retenido1");
                    this._Retenido1 = value;
                    this.SendPropertyChanged("Retenido1");
                }
            }
        }

        public decimal? Retenido2
        {
            get
            {
                return this._Retenido2;
            }
            set
            {
                if (this._Retenido2 != value)
                {
                    this.SendPropertyChanging("Retenido2");
                    this._Retenido2 = value;
                    this.SendPropertyChanged("Retenido2");
                }
            }
        }

        public decimal? RetenidoPorcentaje
        {
            get
            {
                return this._RetenidoPorcentaje;
            }
            set
            {
                if (this._RetenidoPorcentaje != value)
                {
                    this.SendPropertyChanging("RetenidoPorcentaje");
                    this._RetenidoPorcentaje = value;
                    this.SendPropertyChanged("RetenidoPorcentaje");
                }
            }
        }

        public decimal? RetenidoAcumulado
        {
            get
            {
                return this._RetenidoAcumulado;
            }
            set
            {
                if (this._RetenidoAcumulado != value)
                {
                    this.SendPropertyChanging("RetenidoAcumulado");
                    this._RetenidoAcumulado = value;
                    this.SendPropertyChanged("RetenidoAcumulado");
                }
            }
        }

        public decimal? PorcentajePasa
        {
            get
            {
                return this._PorcentajePasa;
            }
            set
            {
                if (this._PorcentajePasa != value)
                {
                    this.SendPropertyChanging("PorcentajePasa");
                    this._PorcentajePasa = value;
                    this.SendPropertyChanged("PorcentajePasa");
                }
            }
        }

        public virtual Granulometria Granulometria
        {
            get
            {
                return this._Granulometria;
            }
            set
            {
                if (this._Granulometria != value)
                {
                    this.SendPropertyChanging("Granulometria");
                    this._Granulometria = value;
                    this.SendPropertyChanged("Granulometria");
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          Granulometriadetalle toCompare = obj as Granulometriadetalle;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.IdDetalle, toCompare.IdDetalle))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + IdDetalle.GetHashCode();
          return hashCode;
        }

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
