//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 29/1/2025 9:33:11 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Sistema.Proctor.Data.Entities
{
    public partial class EnsayoProctor : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private int _Idensayo;

        private int? _Idmuestra;

        private DateTime? _FechaEnsayo;

        private string _Norma;

        private string _MetodoUtilizado;

        private float? _PesoMartilloLb;

        private float? _PesoMaterialG;

        private float? _TemperaturaSecado;

        private float? _DiametroMoldeCm;

        private float? _AlturaMoldeCm;

        private int? _NumCapas;

        private int? _NumGolpes;

        private string _TipoProctor;

        private IList<ResultadosProctor> _ResultadosProctors;

        private Muestra _Muestra;

        public EnsayoProctor()
        {
            this._ResultadosProctors = new List<ResultadosProctor>();
            OnCreated();
        }

        public int Idensayo
        {
            get
            {
                return this._Idensayo;
            }
            set
            {
                if (this._Idensayo != value)
                {
                    this.SendPropertyChanging("Idensayo");
                    this._Idensayo = value;
                    this.SendPropertyChanged("Idensayo");
                }
            }
        }

        public int? Idmuestra
        {
            get
            {
                return this._Idmuestra;
            }
            set
            {
                if (this._Idmuestra != value)
                {
                    this.SendPropertyChanging("Idmuestra");
                    this._Idmuestra = value;
                    this.SendPropertyChanged("Idmuestra");
                }
            }
        }

        public DateTime? FechaEnsayo
        {
            get
            {
                return this._FechaEnsayo;
            }
            set
            {
                if (this._FechaEnsayo != value)
                {
                    this.SendPropertyChanging("FechaEnsayo");
                    this._FechaEnsayo = value;
                    this.SendPropertyChanged("FechaEnsayo");
                }
            }
        }

        public string Norma
        {
            get
            {
                return this._Norma;
            }
            set
            {
                if (this._Norma != value)
                {
                    this.SendPropertyChanging("Norma");
                    this._Norma = value;
                    this.SendPropertyChanged("Norma");
                }
            }
        }

        public string MetodoUtilizado
        {
            get
            {
                return this._MetodoUtilizado;
            }
            set
            {
                if (this._MetodoUtilizado != value)
                {
                    this.SendPropertyChanging("MetodoUtilizado");
                    this._MetodoUtilizado = value;
                    this.SendPropertyChanged("MetodoUtilizado");
                }
            }
        }

        public float? PesoMartilloLb
        {
            get
            {
                return this._PesoMartilloLb;
            }
            set
            {
                if (this._PesoMartilloLb != value)
                {
                    this.SendPropertyChanging("PesoMartilloLb");
                    this._PesoMartilloLb = value;
                    this.SendPropertyChanged("PesoMartilloLb");
                }
            }
        }

        public float? PesoMaterialG
        {
            get
            {
                return this._PesoMaterialG;
            }
            set
            {
                if (this._PesoMaterialG != value)
                {
                    this.SendPropertyChanging("PesoMaterialG");
                    this._PesoMaterialG = value;
                    this.SendPropertyChanged("PesoMaterialG");
                }
            }
        }

        public float? TemperaturaSecado
        {
            get
            {
                return this._TemperaturaSecado;
            }
            set
            {
                if (this._TemperaturaSecado != value)
                {
                    this.SendPropertyChanging("TemperaturaSecado");
                    this._TemperaturaSecado = value;
                    this.SendPropertyChanged("TemperaturaSecado");
                }
            }
        }

        public float? DiametroMoldeCm
        {
            get
            {
                return this._DiametroMoldeCm;
            }
            set
            {
                if (this._DiametroMoldeCm != value)
                {
                    this.SendPropertyChanging("DiametroMoldeCm");
                    this._DiametroMoldeCm = value;
                    this.SendPropertyChanged("DiametroMoldeCm");
                }
            }
        }

        public float? AlturaMoldeCm
        {
            get
            {
                return this._AlturaMoldeCm;
            }
            set
            {
                if (this._AlturaMoldeCm != value)
                {
                    this.SendPropertyChanging("AlturaMoldeCm");
                    this._AlturaMoldeCm = value;
                    this.SendPropertyChanged("AlturaMoldeCm");
                }
            }
        }

        public int? NumCapas
        {
            get
            {
                return this._NumCapas;
            }
            set
            {
                if (this._NumCapas != value)
                {
                    this.SendPropertyChanging("NumCapas");
                    this._NumCapas = value;
                    this.SendPropertyChanged("NumCapas");
                }
            }
        }

        public int? NumGolpes
        {
            get
            {
                return this._NumGolpes;
            }
            set
            {
                if (this._NumGolpes != value)
                {
                    this.SendPropertyChanging("NumGolpes");
                    this._NumGolpes = value;
                    this.SendPropertyChanged("NumGolpes");
                }
            }
        }

        public string TipoProctor
        {
            get
            {
                return this._TipoProctor;
            }
            set
            {
                if (this._TipoProctor != value)
                {
                    this.SendPropertyChanging("TipoProctor");
                    this._TipoProctor = value;
                    this.SendPropertyChanged("TipoProctor");
                }
            }
        }

        public virtual IList<ResultadosProctor> ResultadosProctors
        {
            get
            {
                return this._ResultadosProctors;
            }
            set
            {
                this._ResultadosProctors = value;
            }
        }

        public virtual Muestra Muestra
        {
            get
            {
                return this._Muestra;
            }
            set
            {
                if (this._Muestra != value)
                {
                    this.SendPropertyChanging("Muestra");
                    this._Muestra = value;
                    this.SendPropertyChanged("Muestra");
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          EnsayoProctor toCompare = obj as EnsayoProctor;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Idensayo, toCompare.Idensayo))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Idensayo.GetHashCode();
          return hashCode;
        }

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
