//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 12/2/2025 3:01:04 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Sistema.Proctor.Data.Entities
{
    public partial class Parametro : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private long _Idparametro;

        private string _CodigoProyecto;

        private int _SiguienteCodigoProyecto;

        public Parametro()
        {
            OnCreated();
        }

        public long Idparametro
        {
            get
            {
                return this._Idparametro;
            }
            set
            {
                if (this._Idparametro != value)
                {
                    this.SendPropertyChanging("Idparametro");
                    this._Idparametro = value;
                    this.SendPropertyChanged("Idparametro");
                }
            }
        }

        public string CodigoProyecto
        {
            get
            {
                return this._CodigoProyecto;
            }
            set
            {
                if (this._CodigoProyecto != value)
                {
                    this.SendPropertyChanging("CodigoProyecto");
                    this._CodigoProyecto = value;
                    this.SendPropertyChanged("CodigoProyecto");
                }
            }
        }

        public int SiguienteCodigoProyecto
        {
            get
            {
                return this._SiguienteCodigoProyecto;
            }
            set
            {
                if (this._SiguienteCodigoProyecto != value)
                {
                    this.SendPropertyChanging("SiguienteCodigoProyecto");
                    this._SiguienteCodigoProyecto = value;
                    this.SendPropertyChanged("SiguienteCodigoProyecto");
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          Parametro toCompare = obj as Parametro;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Idparametro, toCompare.Idparametro))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Idparametro.GetHashCode();
          return hashCode;
        }

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
