//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 15/7/2025 1:20:22 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Sistema.Proctor.Data.Entities
{
    public partial class EnsayoLimite : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private int _Idensayolimites;

        private decimal? _ProfundidadInicial;

        private decimal? _ProfundidadFinal;

        private string _InformeNo;

        private string _Muestra;

        private DateTime? _FechaIngreso;

        private string _DescripcionMaterial;

        private int? _MuestraNo;

        private DateTime? _FechaEmision;

        private string _MetodoMuestreo;

        private DateTime? _FechaMuestreo;

        private string _CodigoIngreso;

        private DateTime? _FechaEnsayoInicio;

        private DateTime? _FechaEnsayoFin;

        private decimal? _PasaTamiz4;

        private decimal? _PasaTamiz10;

        private decimal? _PasaTamiz40;

        private decimal? _PasaTamiz200;

        private int? _CreatedBy;

        private DateTime _CreatedAt;

        private int? _UpdatedBy;

        private DateTime? _UpdateAt;

        private int? _EnsayadoPor;

        private int? _RevisadoPor;

        private int? _VerificadoPor;

        private int? _AutorizadoPor;

        private decimal? _LimiteLiquido;

        private decimal? _LimitePlastico;

        private decimal? _IndicePlasticidad;

        private IList<LimiteLiquido> _LimiteLiquidos;

        private IList<LimitePlastico> _LimitePlasticos;

        public EnsayoLimite()
        {
            this._LimiteLiquidos = new List<LimiteLiquido>();
            this._LimitePlasticos = new List<LimitePlastico>();
            OnCreated();
        }

        public int Idensayolimites
        {
            get
            {
                return this._Idensayolimites;
            }
            set
            {
                if (this._Idensayolimites != value)
                {
                    this.SendPropertyChanging("Idensayolimites");
                    this._Idensayolimites = value;
                    this.SendPropertyChanged("Idensayolimites");
                }
            }
        }

        public decimal? ProfundidadInicial
        {
            get
            {
                return this._ProfundidadInicial;
            }
            set
            {
                if (this._ProfundidadInicial != value)
                {
                    this.SendPropertyChanging("ProfundidadInicial");
                    this._ProfundidadInicial = value;
                    this.SendPropertyChanged("ProfundidadInicial");
                }
            }
        }

        public decimal? ProfundidadFinal
        {
            get
            {
                return this._ProfundidadFinal;
            }
            set
            {
                if (this._ProfundidadFinal != value)
                {
                    this.SendPropertyChanging("ProfundidadFinal");
                    this._ProfundidadFinal = value;
                    this.SendPropertyChanged("ProfundidadFinal");
                }
            }
        }

        public string InformeNo
        {
            get
            {
                return this._InformeNo;
            }
            set
            {
                if (this._InformeNo != value)
                {
                    this.SendPropertyChanging("InformeNo");
                    this._InformeNo = value;
                    this.SendPropertyChanged("InformeNo");
                }
            }
        }

        public string Muestra
        {
            get
            {
                return this._Muestra;
            }
            set
            {
                if (this._Muestra != value)
                {
                    this.SendPropertyChanging("Muestra");
                    this._Muestra = value;
                    this.SendPropertyChanged("Muestra");
                }
            }
        }

        public DateTime? FechaIngreso
        {
            get
            {
                return this._FechaIngreso;
            }
            set
            {
                if (this._FechaIngreso != value)
                {
                    this.SendPropertyChanging("FechaIngreso");
                    this._FechaIngreso = value;
                    this.SendPropertyChanged("FechaIngreso");
                }
            }
        }

        public string DescripcionMaterial
        {
            get
            {
                return this._DescripcionMaterial;
            }
            set
            {
                if (this._DescripcionMaterial != value)
                {
                    this.SendPropertyChanging("DescripcionMaterial");
                    this._DescripcionMaterial = value;
                    this.SendPropertyChanged("DescripcionMaterial");
                }
            }
        }

        public int? MuestraNo
        {
            get
            {
                return this._MuestraNo;
            }
            set
            {
                if (this._MuestraNo != value)
                {
                    this.SendPropertyChanging("MuestraNo");
                    this._MuestraNo = value;
                    this.SendPropertyChanged("MuestraNo");
                }
            }
        }

        public DateTime? FechaEmision
        {
            get
            {
                return this._FechaEmision;
            }
            set
            {
                if (this._FechaEmision != value)
                {
                    this.SendPropertyChanging("FechaEmision");
                    this._FechaEmision = value;
                    this.SendPropertyChanged("FechaEmision");
                }
            }
        }

        public string MetodoMuestreo
        {
            get
            {
                return this._MetodoMuestreo;
            }
            set
            {
                if (this._MetodoMuestreo != value)
                {
                    this.SendPropertyChanging("MetodoMuestreo");
                    this._MetodoMuestreo = value;
                    this.SendPropertyChanged("MetodoMuestreo");
                }
            }
        }

        public DateTime? FechaMuestreo
        {
            get
            {
                return this._FechaMuestreo;
            }
            set
            {
                if (this._FechaMuestreo != value)
                {
                    this.SendPropertyChanging("FechaMuestreo");
                    this._FechaMuestreo = value;
                    this.SendPropertyChanged("FechaMuestreo");
                }
            }
        }

        public string CodigoIngreso
        {
            get
            {
                return this._CodigoIngreso;
            }
            set
            {
                if (this._CodigoIngreso != value)
                {
                    this.SendPropertyChanging("CodigoIngreso");
                    this._CodigoIngreso = value;
                    this.SendPropertyChanged("CodigoIngreso");
                }
            }
        }

        public DateTime? FechaEnsayoInicio
        {
            get
            {
                return this._FechaEnsayoInicio;
            }
            set
            {
                if (this._FechaEnsayoInicio != value)
                {
                    this.SendPropertyChanging("FechaEnsayoInicio");
                    this._FechaEnsayoInicio = value;
                    this.SendPropertyChanged("FechaEnsayoInicio");
                }
            }
        }

        public DateTime? FechaEnsayoFin
        {
            get
            {
                return this._FechaEnsayoFin;
            }
            set
            {
                if (this._FechaEnsayoFin != value)
                {
                    this.SendPropertyChanging("FechaEnsayoFin");
                    this._FechaEnsayoFin = value;
                    this.SendPropertyChanged("FechaEnsayoFin");
                }
            }
        }

        public decimal? PasaTamiz4
        {
            get
            {
                return this._PasaTamiz4;
            }
            set
            {
                if (this._PasaTamiz4 != value)
                {
                    this.SendPropertyChanging("PasaTamiz4");
                    this._PasaTamiz4 = value;
                    this.SendPropertyChanged("PasaTamiz4");
                }
            }
        }

        public decimal? PasaTamiz10
        {
            get
            {
                return this._PasaTamiz10;
            }
            set
            {
                if (this._PasaTamiz10 != value)
                {
                    this.SendPropertyChanging("PasaTamiz10");
                    this._PasaTamiz10 = value;
                    this.SendPropertyChanged("PasaTamiz10");
                }
            }
        }

        public decimal? PasaTamiz40
        {
            get
            {
                return this._PasaTamiz40;
            }
            set
            {
                if (this._PasaTamiz40 != value)
                {
                    this.SendPropertyChanging("PasaTamiz40");
                    this._PasaTamiz40 = value;
                    this.SendPropertyChanged("PasaTamiz40");
                }
            }
        }

        public decimal? PasaTamiz200
        {
            get
            {
                return this._PasaTamiz200;
            }
            set
            {
                if (this._PasaTamiz200 != value)
                {
                    this.SendPropertyChanging("PasaTamiz200");
                    this._PasaTamiz200 = value;
                    this.SendPropertyChanged("PasaTamiz200");
                }
            }
        }

        public int? CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                if (this._CreatedBy != value)
                {
                    this.SendPropertyChanging("CreatedBy");
                    this._CreatedBy = value;
                    this.SendPropertyChanged("CreatedBy");
                }
            }
        }

        public DateTime CreatedAt
        {
            get
            {
                return this._CreatedAt;
            }
            set
            {
                if (this._CreatedAt != value)
                {
                    this.SendPropertyChanging("CreatedAt");
                    this._CreatedAt = value;
                    this.SendPropertyChanged("CreatedAt");
                }
            }
        }

        public int? UpdatedBy
        {
            get
            {
                return this._UpdatedBy;
            }
            set
            {
                if (this._UpdatedBy != value)
                {
                    this.SendPropertyChanging("UpdatedBy");
                    this._UpdatedBy = value;
                    this.SendPropertyChanged("UpdatedBy");
                }
            }
        }

        public DateTime? UpdateAt
        {
            get
            {
                return this._UpdateAt;
            }
            set
            {
                if (this._UpdateAt != value)
                {
                    this.SendPropertyChanging("UpdateAt");
                    this._UpdateAt = value;
                    this.SendPropertyChanged("UpdateAt");
                }
            }
        }

        public int? EnsayadoPor
        {
            get
            {
                return this._EnsayadoPor;
            }
            set
            {
                if (this._EnsayadoPor != value)
                {
                    this.SendPropertyChanging("EnsayadoPor");
                    this._EnsayadoPor = value;
                    this.SendPropertyChanged("EnsayadoPor");
                }
            }
        }

        public int? RevisadoPor
        {
            get
            {
                return this._RevisadoPor;
            }
            set
            {
                if (this._RevisadoPor != value)
                {
                    this.SendPropertyChanging("RevisadoPor");
                    this._RevisadoPor = value;
                    this.SendPropertyChanged("RevisadoPor");
                }
            }
        }

        public int? VerificadoPor
        {
            get
            {
                return this._VerificadoPor;
            }
            set
            {
                if (this._VerificadoPor != value)
                {
                    this.SendPropertyChanging("VerificadoPor");
                    this._VerificadoPor = value;
                    this.SendPropertyChanged("VerificadoPor");
                }
            }
        }

        public int? AutorizadoPor
        {
            get
            {
                return this._AutorizadoPor;
            }
            set
            {
                if (this._AutorizadoPor != value)
                {
                    this.SendPropertyChanging("AutorizadoPor");
                    this._AutorizadoPor = value;
                    this.SendPropertyChanged("AutorizadoPor");
                }
            }
        }

        public decimal? LimiteLiquido
        {
            get
            {
                return this._LimiteLiquido;
            }
            set
            {
                if (this._LimiteLiquido != value)
                {
                    this.SendPropertyChanging("LimiteLiquido");
                    this._LimiteLiquido = value;
                    this.SendPropertyChanged("LimiteLiquido");
                }
            }
        }

        public decimal? LimitePlastico
        {
            get
            {
                return this._LimitePlastico;
            }
            set
            {
                if (this._LimitePlastico != value)
                {
                    this.SendPropertyChanging("LimitePlastico");
                    this._LimitePlastico = value;
                    this.SendPropertyChanged("LimitePlastico");
                }
            }
        }

        public decimal? IndicePlasticidad
        {
            get
            {
                return this._IndicePlasticidad;
            }
            set
            {
                if (this._IndicePlasticidad != value)
                {
                    this.SendPropertyChanging("IndicePlasticidad");
                    this._IndicePlasticidad = value;
                    this.SendPropertyChanged("IndicePlasticidad");
                }
            }
        }

        public virtual IList<LimiteLiquido> LimiteLiquidos
        {
            get
            {
                return this._LimiteLiquidos;
            }
            set
            {
                this._LimiteLiquidos = value;
            }
        }

        public virtual IList<LimitePlastico> LimitePlasticos
        {
            get
            {
                return this._LimitePlasticos;
            }
            set
            {
                this._LimitePlasticos = value;
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          EnsayoLimite toCompare = obj as EnsayoLimite;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Idensayolimites, toCompare.Idensayolimites))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Idensayolimites.GetHashCode();
          return hashCode;
        }

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
