//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 15/7/2025 1:20:22 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Sistema.Proctor.Data.Entities
{
    public partial class EnsayoHumedad : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private int _Idensayohumedad;

        private string _InformeNumero;

        private int? _Idmuestra;

        private DateTime? _FechaIngreso;

        private string _DescripcionMaterial;

        private DateTime? _FechaEmision;

        private string _MetodoMuestreo;

        private DateTime? _FechaMuestreo;

        private DateTime? _FechaInicio;

        private DateTime? _FechaFin;

        private string _CodigoIngreso;

        private string _Metodo;

        private string _RealizadoEn;

        private int? _CreatedBy;

        private DateTime _CreatedAt;

        private int? _UpdatedBy;

        private DateTime? _UpdateAt;

        private int? _EnsayadoPor;

        private int? _RevisadoPor;

        private int? _VerificadoPor;

        private int? _AutorizadoPor;

        private Muestra _Muestra;

        private IList<ResultadoHumedad> _ResultadoHumedads;

        public EnsayoHumedad()
        {
            this._ResultadoHumedads = new List<ResultadoHumedad>();
            OnCreated();
        }

        public int Idensayohumedad
        {
            get
            {
                return this._Idensayohumedad;
            }
            set
            {
                if (this._Idensayohumedad != value)
                {
                    this.SendPropertyChanging("Idensayohumedad");
                    this._Idensayohumedad = value;
                    this.SendPropertyChanged("Idensayohumedad");
                }
            }
        }

        public string InformeNumero
        {
            get
            {
                return this._InformeNumero;
            }
            set
            {
                if (this._InformeNumero != value)
                {
                    this.SendPropertyChanging("InformeNumero");
                    this._InformeNumero = value;
                    this.SendPropertyChanged("InformeNumero");
                }
            }
        }

        public int? Idmuestra
        {
            get
            {
                return this._Idmuestra;
            }
            set
            {
                if (this._Idmuestra != value)
                {
                    this.SendPropertyChanging("Idmuestra");
                    this._Idmuestra = value;
                    this.SendPropertyChanged("Idmuestra");
                }
            }
        }

        public DateTime? FechaIngreso
        {
            get
            {
                return this._FechaIngreso;
            }
            set
            {
                if (this._FechaIngreso != value)
                {
                    this.SendPropertyChanging("FechaIngreso");
                    this._FechaIngreso = value;
                    this.SendPropertyChanged("FechaIngreso");
                }
            }
        }

        public string DescripcionMaterial
        {
            get
            {
                return this._DescripcionMaterial;
            }
            set
            {
                if (this._DescripcionMaterial != value)
                {
                    this.SendPropertyChanging("DescripcionMaterial");
                    this._DescripcionMaterial = value;
                    this.SendPropertyChanged("DescripcionMaterial");
                }
            }
        }

        public DateTime? FechaEmision
        {
            get
            {
                return this._FechaEmision;
            }
            set
            {
                if (this._FechaEmision != value)
                {
                    this.SendPropertyChanging("FechaEmision");
                    this._FechaEmision = value;
                    this.SendPropertyChanged("FechaEmision");
                }
            }
        }

        public string MetodoMuestreo
        {
            get
            {
                return this._MetodoMuestreo;
            }
            set
            {
                if (this._MetodoMuestreo != value)
                {
                    this.SendPropertyChanging("MetodoMuestreo");
                    this._MetodoMuestreo = value;
                    this.SendPropertyChanged("MetodoMuestreo");
                }
            }
        }

        public DateTime? FechaMuestreo
        {
            get
            {
                return this._FechaMuestreo;
            }
            set
            {
                if (this._FechaMuestreo != value)
                {
                    this.SendPropertyChanging("FechaMuestreo");
                    this._FechaMuestreo = value;
                    this.SendPropertyChanged("FechaMuestreo");
                }
            }
        }

        public DateTime? FechaInicio
        {
            get
            {
                return this._FechaInicio;
            }
            set
            {
                if (this._FechaInicio != value)
                {
                    this.SendPropertyChanging("FechaInicio");
                    this._FechaInicio = value;
                    this.SendPropertyChanged("FechaInicio");
                }
            }
        }

        public DateTime? FechaFin
        {
            get
            {
                return this._FechaFin;
            }
            set
            {
                if (this._FechaFin != value)
                {
                    this.SendPropertyChanging("FechaFin");
                    this._FechaFin = value;
                    this.SendPropertyChanged("FechaFin");
                }
            }
        }

        public string CodigoIngreso
        {
            get
            {
                return this._CodigoIngreso;
            }
            set
            {
                if (this._CodigoIngreso != value)
                {
                    this.SendPropertyChanging("CodigoIngreso");
                    this._CodigoIngreso = value;
                    this.SendPropertyChanged("CodigoIngreso");
                }
            }
        }

        public string Metodo
        {
            get
            {
                return this._Metodo;
            }
            set
            {
                if (this._Metodo != value)
                {
                    this.SendPropertyChanging("Metodo");
                    this._Metodo = value;
                    this.SendPropertyChanged("Metodo");
                }
            }
        }

        public string RealizadoEn
        {
            get
            {
                return this._RealizadoEn;
            }
            set
            {
                if (this._RealizadoEn != value)
                {
                    this.SendPropertyChanging("RealizadoEn");
                    this._RealizadoEn = value;
                    this.SendPropertyChanged("RealizadoEn");
                }
            }
        }

        public int? CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                if (this._CreatedBy != value)
                {
                    this.SendPropertyChanging("CreatedBy");
                    this._CreatedBy = value;
                    this.SendPropertyChanged("CreatedBy");
                }
            }
        }

        public DateTime CreatedAt
        {
            get
            {
                return this._CreatedAt;
            }
            set
            {
                if (this._CreatedAt != value)
                {
                    this.SendPropertyChanging("CreatedAt");
                    this._CreatedAt = value;
                    this.SendPropertyChanged("CreatedAt");
                }
            }
        }

        public int? UpdatedBy
        {
            get
            {
                return this._UpdatedBy;
            }
            set
            {
                if (this._UpdatedBy != value)
                {
                    this.SendPropertyChanging("UpdatedBy");
                    this._UpdatedBy = value;
                    this.SendPropertyChanged("UpdatedBy");
                }
            }
        }

        public DateTime? UpdateAt
        {
            get
            {
                return this._UpdateAt;
            }
            set
            {
                if (this._UpdateAt != value)
                {
                    this.SendPropertyChanging("UpdateAt");
                    this._UpdateAt = value;
                    this.SendPropertyChanged("UpdateAt");
                }
            }
        }

        public int? EnsayadoPor
        {
            get
            {
                return this._EnsayadoPor;
            }
            set
            {
                if (this._EnsayadoPor != value)
                {
                    this.SendPropertyChanging("EnsayadoPor");
                    this._EnsayadoPor = value;
                    this.SendPropertyChanged("EnsayadoPor");
                }
            }
        }

        public int? RevisadoPor
        {
            get
            {
                return this._RevisadoPor;
            }
            set
            {
                if (this._RevisadoPor != value)
                {
                    this.SendPropertyChanging("RevisadoPor");
                    this._RevisadoPor = value;
                    this.SendPropertyChanged("RevisadoPor");
                }
            }
        }

        public int? VerificadoPor
        {
            get
            {
                return this._VerificadoPor;
            }
            set
            {
                if (this._VerificadoPor != value)
                {
                    this.SendPropertyChanging("VerificadoPor");
                    this._VerificadoPor = value;
                    this.SendPropertyChanged("VerificadoPor");
                }
            }
        }

        public int? AutorizadoPor
        {
            get
            {
                return this._AutorizadoPor;
            }
            set
            {
                if (this._AutorizadoPor != value)
                {
                    this.SendPropertyChanging("AutorizadoPor");
                    this._AutorizadoPor = value;
                    this.SendPropertyChanged("AutorizadoPor");
                }
            }
        }

        public virtual Muestra Muestra
        {
            get
            {
                return this._Muestra;
            }
            set
            {
                if (this._Muestra != value)
                {
                    this.SendPropertyChanging("Muestra");
                    this._Muestra = value;
                    this.SendPropertyChanged("Muestra");
                }
            }
        }

        public virtual IList<ResultadoHumedad> ResultadoHumedads
        {
            get
            {
                return this._ResultadoHumedads;
            }
            set
            {
                this._ResultadoHumedads = value;
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          EnsayoHumedad toCompare = obj as EnsayoHumedad;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Idensayohumedad, toCompare.Idensayohumedad))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Idensayohumedad.GetHashCode();
          return hashCode;
        }

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
