//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 15/7/2025 1:20:22 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Sistema.Proctor.Data.Entities
{
    public partial class Clasificacionsuc : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private int _IdClasificacion;

        private int _IdMuestra;

        private string _GrupoSUCS;

        private string _Descripcion;

        private Muestra _Muestra;

        public Clasificacionsuc()
        {
            OnCreated();
        }

        public int IdClasificacion
        {
            get
            {
                return this._IdClasificacion;
            }
            set
            {
                if (this._IdClasificacion != value)
                {
                    this.SendPropertyChanging("IdClasificacion");
                    this._IdClasificacion = value;
                    this.SendPropertyChanged("IdClasificacion");
                }
            }
        }

        public int IdMuestra
        {
            get
            {
                return this._IdMuestra;
            }
            set
            {
                if (this._IdMuestra != value)
                {
                    this.SendPropertyChanging("IdMuestra");
                    this._IdMuestra = value;
                    this.SendPropertyChanged("IdMuestra");
                }
            }
        }

        public string GrupoSUCS
        {
            get
            {
                return this._GrupoSUCS;
            }
            set
            {
                if (this._GrupoSUCS != value)
                {
                    this.SendPropertyChanging("GrupoSUCS");
                    this._GrupoSUCS = value;
                    this.SendPropertyChanged("GrupoSUCS");
                }
            }
        }

        public string Descripcion
        {
            get
            {
                return this._Descripcion;
            }
            set
            {
                if (this._Descripcion != value)
                {
                    this.SendPropertyChanging("Descripcion");
                    this._Descripcion = value;
                    this.SendPropertyChanged("Descripcion");
                }
            }
        }

        public virtual Muestra Muestra
        {
            get
            {
                return this._Muestra;
            }
            set
            {
                if (this._Muestra != value)
                {
                    this.SendPropertyChanging("Muestra");
                    this._Muestra = value;
                    this.SendPropertyChanged("Muestra");
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          Clasificacionsuc toCompare = obj as Clasificacionsuc;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.IdClasificacion, toCompare.IdClasificacion))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + IdClasificacion.GetHashCode();
          return hashCode;
        }

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
