//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 15/7/2025 1:20:22 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Sistema.Proctor.Data.Entities
{
    public partial class Granulometria : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private int _IdGranulometria;

        private int _Idensayogranulometria;

        private decimal? _Arena;

        private decimal? _Limo;

        private decimal? _Arcilla;

        private decimal? _Grava;

        private decimal? _PesoInicial;

        private decimal? _RetenidoTamiz4;

        private decimal? _MaterialPasaTamiz4;

        private decimal? _PesoRepresentativo;

        private decimal? _PesoMuestraLuegoLavado;

        private decimal? _PasaTamizPorLavado;

        private decimal? _PasaTamizPorTamizado;

        private int? _CreatedBy;

        private DateTime _CreatedAt;

        private int? _UpdatedBy;

        private DateTime? _UpdateAt;

        private int? _EnsayadoPor;

        private int? _RevisadoPor;

        private int? _VerificadoPor;

        private int? _AutorizadoPor;

        private EnsayoGranulometria _EnsayoGranulometria;

        private IList<Granulometriadetalle> _Granulometriadetalles;

        public Granulometria()
        {
            this._Granulometriadetalles = new List<Granulometriadetalle>();
            OnCreated();
        }

        public int IdGranulometria
        {
            get
            {
                return this._IdGranulometria;
            }
            set
            {
                if (this._IdGranulometria != value)
                {
                    this.SendPropertyChanging("IdGranulometria");
                    this._IdGranulometria = value;
                    this.SendPropertyChanged("IdGranulometria");
                }
            }
        }

        public int Idensayogranulometria
        {
            get
            {
                return this._Idensayogranulometria;
            }
            set
            {
                if (this._Idensayogranulometria != value)
                {
                    this.SendPropertyChanging("Idensayogranulometria");
                    this._Idensayogranulometria = value;
                    this.SendPropertyChanged("Idensayogranulometria");
                }
            }
        }

        public decimal? Arena
        {
            get
            {
                return this._Arena;
            }
            set
            {
                if (this._Arena != value)
                {
                    this.SendPropertyChanging("Arena");
                    this._Arena = value;
                    this.SendPropertyChanged("Arena");
                }
            }
        }

        public decimal? Limo
        {
            get
            {
                return this._Limo;
            }
            set
            {
                if (this._Limo != value)
                {
                    this.SendPropertyChanging("Limo");
                    this._Limo = value;
                    this.SendPropertyChanged("Limo");
                }
            }
        }

        public decimal? Arcilla
        {
            get
            {
                return this._Arcilla;
            }
            set
            {
                if (this._Arcilla != value)
                {
                    this.SendPropertyChanging("Arcilla");
                    this._Arcilla = value;
                    this.SendPropertyChanged("Arcilla");
                }
            }
        }

        public decimal? Grava
        {
            get
            {
                return this._Grava;
            }
            set
            {
                if (this._Grava != value)
                {
                    this.SendPropertyChanging("Grava");
                    this._Grava = value;
                    this.SendPropertyChanged("Grava");
                }
            }
        }

        public decimal? PesoInicial
        {
            get
            {
                return this._PesoInicial;
            }
            set
            {
                if (this._PesoInicial != value)
                {
                    this.SendPropertyChanging("PesoInicial");
                    this._PesoInicial = value;
                    this.SendPropertyChanged("PesoInicial");
                }
            }
        }

        public decimal? RetenidoTamiz4
        {
            get
            {
                return this._RetenidoTamiz4;
            }
            set
            {
                if (this._RetenidoTamiz4 != value)
                {
                    this.SendPropertyChanging("RetenidoTamiz4");
                    this._RetenidoTamiz4 = value;
                    this.SendPropertyChanged("RetenidoTamiz4");
                }
            }
        }

        public decimal? MaterialPasaTamiz4
        {
            get
            {
                return this._MaterialPasaTamiz4;
            }
            set
            {
                if (this._MaterialPasaTamiz4 != value)
                {
                    this.SendPropertyChanging("MaterialPasaTamiz4");
                    this._MaterialPasaTamiz4 = value;
                    this.SendPropertyChanged("MaterialPasaTamiz4");
                }
            }
        }

        public decimal? PesoRepresentativo
        {
            get
            {
                return this._PesoRepresentativo;
            }
            set
            {
                if (this._PesoRepresentativo != value)
                {
                    this.SendPropertyChanging("PesoRepresentativo");
                    this._PesoRepresentativo = value;
                    this.SendPropertyChanged("PesoRepresentativo");
                }
            }
        }

        public decimal? PesoMuestraLuegoLavado
        {
            get
            {
                return this._PesoMuestraLuegoLavado;
            }
            set
            {
                if (this._PesoMuestraLuegoLavado != value)
                {
                    this.SendPropertyChanging("PesoMuestraLuegoLavado");
                    this._PesoMuestraLuegoLavado = value;
                    this.SendPropertyChanged("PesoMuestraLuegoLavado");
                }
            }
        }

        public decimal? PasaTamizPorLavado
        {
            get
            {
                return this._PasaTamizPorLavado;
            }
            set
            {
                if (this._PasaTamizPorLavado != value)
                {
                    this.SendPropertyChanging("PasaTamizPorLavado");
                    this._PasaTamizPorLavado = value;
                    this.SendPropertyChanged("PasaTamizPorLavado");
                }
            }
        }

        public decimal? PasaTamizPorTamizado
        {
            get
            {
                return this._PasaTamizPorTamizado;
            }
            set
            {
                if (this._PasaTamizPorTamizado != value)
                {
                    this.SendPropertyChanging("PasaTamizPorTamizado");
                    this._PasaTamizPorTamizado = value;
                    this.SendPropertyChanged("PasaTamizPorTamizado");
                }
            }
        }

        public int? CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                if (this._CreatedBy != value)
                {
                    this.SendPropertyChanging("CreatedBy");
                    this._CreatedBy = value;
                    this.SendPropertyChanged("CreatedBy");
                }
            }
        }

        public DateTime CreatedAt
        {
            get
            {
                return this._CreatedAt;
            }
            set
            {
                if (this._CreatedAt != value)
                {
                    this.SendPropertyChanging("CreatedAt");
                    this._CreatedAt = value;
                    this.SendPropertyChanged("CreatedAt");
                }
            }
        }

        public int? UpdatedBy
        {
            get
            {
                return this._UpdatedBy;
            }
            set
            {
                if (this._UpdatedBy != value)
                {
                    this.SendPropertyChanging("UpdatedBy");
                    this._UpdatedBy = value;
                    this.SendPropertyChanged("UpdatedBy");
                }
            }
        }

        public DateTime? UpdateAt
        {
            get
            {
                return this._UpdateAt;
            }
            set
            {
                if (this._UpdateAt != value)
                {
                    this.SendPropertyChanging("UpdateAt");
                    this._UpdateAt = value;
                    this.SendPropertyChanged("UpdateAt");
                }
            }
        }

        public int? EnsayadoPor
        {
            get
            {
                return this._EnsayadoPor;
            }
            set
            {
                if (this._EnsayadoPor != value)
                {
                    this.SendPropertyChanging("EnsayadoPor");
                    this._EnsayadoPor = value;
                    this.SendPropertyChanged("EnsayadoPor");
                }
            }
        }

        public int? RevisadoPor
        {
            get
            {
                return this._RevisadoPor;
            }
            set
            {
                if (this._RevisadoPor != value)
                {
                    this.SendPropertyChanging("RevisadoPor");
                    this._RevisadoPor = value;
                    this.SendPropertyChanged("RevisadoPor");
                }
            }
        }

        public int? VerificadoPor
        {
            get
            {
                return this._VerificadoPor;
            }
            set
            {
                if (this._VerificadoPor != value)
                {
                    this.SendPropertyChanging("VerificadoPor");
                    this._VerificadoPor = value;
                    this.SendPropertyChanged("VerificadoPor");
                }
            }
        }

        public int? AutorizadoPor
        {
            get
            {
                return this._AutorizadoPor;
            }
            set
            {
                if (this._AutorizadoPor != value)
                {
                    this.SendPropertyChanging("AutorizadoPor");
                    this._AutorizadoPor = value;
                    this.SendPropertyChanged("AutorizadoPor");
                }
            }
        }

        public virtual EnsayoGranulometria EnsayoGranulometria
        {
            get
            {
                return this._EnsayoGranulometria;
            }
            set
            {
                if (this._EnsayoGranulometria != value)
                {
                    this.SendPropertyChanging("EnsayoGranulometria");
                    this._EnsayoGranulometria = value;
                    this.SendPropertyChanged("EnsayoGranulometria");
                }
            }
        }

        public virtual IList<Granulometriadetalle> Granulometriadetalles
        {
            get
            {
                return this._Granulometriadetalles;
            }
            set
            {
                this._Granulometriadetalles = value;
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          Granulometria toCompare = obj as Granulometria;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.IdGranulometria, toCompare.IdGranulometria))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + IdGranulometria.GetHashCode();
          return hashCode;
        }

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
