//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 15/7/2025 1:20:22 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Sistema.Proctor.Data.Entities
{
    public partial class LimiteLiquido : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private int _Idlimiteliquido;

        private int? _Idensayolimites;

        private int _NumGolpes;

        private string _CodigoTara;

        private decimal? _PesoTara;

        private decimal? _PesoTaraMuestraHumeda;

        private decimal? _PesoTaraMuestraSeca;

        private decimal? _PesoMuestraSeca;

        private decimal? _PesoAgua;

        private decimal? _Humedad;

        private string _Metodo;

        private EnsayoLimite _EnsayoLimite;

        public LimiteLiquido()
        {
            OnCreated();
        }

        public int Idlimiteliquido
        {
            get
            {
                return this._Idlimiteliquido;
            }
            set
            {
                if (this._Idlimiteliquido != value)
                {
                    this.SendPropertyChanging("Idlimiteliquido");
                    this._Idlimiteliquido = value;
                    this.SendPropertyChanged("Idlimiteliquido");
                }
            }
        }

        public int? Idensayolimites
        {
            get
            {
                return this._Idensayolimites;
            }
            set
            {
                if (this._Idensayolimites != value)
                {
                    this.SendPropertyChanging("Idensayolimites");
                    this._Idensayolimites = value;
                    this.SendPropertyChanged("Idensayolimites");
                }
            }
        }

        public int NumGolpes
        {
            get
            {
                return this._NumGolpes;
            }
            set
            {
                if (this._NumGolpes != value)
                {
                    this.SendPropertyChanging("NumGolpes");
                    this._NumGolpes = value;
                    this.SendPropertyChanged("NumGolpes");
                }
            }
        }

        public string CodigoTara
        {
            get
            {
                return this._CodigoTara;
            }
            set
            {
                if (this._CodigoTara != value)
                {
                    this.SendPropertyChanging("CodigoTara");
                    this._CodigoTara = value;
                    this.SendPropertyChanged("CodigoTara");
                }
            }
        }

        public decimal? PesoTara
        {
            get
            {
                return this._PesoTara;
            }
            set
            {
                if (this._PesoTara != value)
                {
                    this.SendPropertyChanging("PesoTara");
                    this._PesoTara = value;
                    this.SendPropertyChanged("PesoTara");
                }
            }
        }

        public decimal? PesoTaraMuestraHumeda
        {
            get
            {
                return this._PesoTaraMuestraHumeda;
            }
            set
            {
                if (this._PesoTaraMuestraHumeda != value)
                {
                    this.SendPropertyChanging("PesoTaraMuestraHumeda");
                    this._PesoTaraMuestraHumeda = value;
                    this.SendPropertyChanged("PesoTaraMuestraHumeda");
                }
            }
        }

        public decimal? PesoTaraMuestraSeca
        {
            get
            {
                return this._PesoTaraMuestraSeca;
            }
            set
            {
                if (this._PesoTaraMuestraSeca != value)
                {
                    this.SendPropertyChanging("PesoTaraMuestraSeca");
                    this._PesoTaraMuestraSeca = value;
                    this.SendPropertyChanged("PesoTaraMuestraSeca");
                }
            }
        }

        public decimal? PesoMuestraSeca
        {
            get
            {
                return this._PesoMuestraSeca;
            }
            set
            {
                if (this._PesoMuestraSeca != value)
                {
                    this.SendPropertyChanging("PesoMuestraSeca");
                    this._PesoMuestraSeca = value;
                    this.SendPropertyChanged("PesoMuestraSeca");
                }
            }
        }

        public decimal? PesoAgua
        {
            get
            {
                return this._PesoAgua;
            }
            set
            {
                if (this._PesoAgua != value)
                {
                    this.SendPropertyChanging("PesoAgua");
                    this._PesoAgua = value;
                    this.SendPropertyChanged("PesoAgua");
                }
            }
        }

        public decimal? Humedad
        {
            get
            {
                return this._Humedad;
            }
            set
            {
                if (this._Humedad != value)
                {
                    this.SendPropertyChanging("Humedad");
                    this._Humedad = value;
                    this.SendPropertyChanged("Humedad");
                }
            }
        }

        public string Metodo
        {
            get
            {
                return this._Metodo;
            }
            set
            {
                if (this._Metodo != value)
                {
                    this.SendPropertyChanging("Metodo");
                    this._Metodo = value;
                    this.SendPropertyChanged("Metodo");
                }
            }
        }

        public virtual EnsayoLimite EnsayoLimite
        {
            get
            {
                return this._EnsayoLimite;
            }
            set
            {
                if (this._EnsayoLimite != value)
                {
                    this.SendPropertyChanging("EnsayoLimite");
                    this._EnsayoLimite = value;
                    this.SendPropertyChanged("EnsayoLimite");
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          LimiteLiquido toCompare = obj as LimiteLiquido;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Idlimiteliquido, toCompare.Idlimiteliquido))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Idlimiteliquido.GetHashCode();
          return hashCode;
        }

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
